name: Build and Publish Docker image

on:
  push:
    branches: [main, changesets]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ secrets.DOCKERHUB_USER }}/lansaver
      #     readme-filepath: ./README.md

      - name: Install dependencies
        run: npm install

      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          publish: npm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/lansaver:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=edspencer/lansaver:buildcache
          cache-to: type=registry,ref=edspencer/lansaver:buildcache,mode=max

  release-to-heroku:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Pull the amd64 image from Docker Hub
        run: |
          docker pull --platform linux/amd64 ${{ secrets.DOCKERHUB_USER }}/lansaver:latest

      - name: Tag the image for Heroku
        run: |
          docker tag ${{ secrets.DOCKERHUB_USER }}/lansaver:latest registry.heroku.com/lansaver/web

      - name: Push the image to Heroku
        run: |
          docker push registry.heroku.com/lansaver/web

      - name: Release the app on Heroku
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/lansaver/formation \
          -d '{ "updates": [{"type": "web", "docker_image": "'$(docker inspect registry.heroku.com/lansaver/web --format={{.Id}})'"}]}' \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-release"
